// <auto-generated />
using System;
using LearningAgents.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningAgents.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LearningAgentsDbContext))]
    [Migration("20260905185859_AddRowVersionToMemoryEntry")]
    partial class AddRowVersionToMemoryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("LearningAgents.Domain.Entities.MemoryChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemoryEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemoryEntryId");

                    b.HasIndex("MessageId");

                    b.ToTable("MemoryChanges");
                });

            modelBuilder.Entity("LearningAgents.Domain.Entities.MemoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TutorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TutorId", "Key")
                        .IsUnique();

                    b.ToTable("MemoryEntries", t =>
                        {
                            t.HasCheckConstraint("CK_MemoryEntries_Key", "Key IN ('memoria_sesion', 'perfil_estudiante', 'mapa_dominio', 'lagunas_o_errores', 'historial_actividades')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "memoria_sesion",
                            SchemaVersion = 1,
                            TutorId = 1,
                            UpdatedAtUtc = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueJson = "{}"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "perfil_estudiante",
                            SchemaVersion = 1,
                            TutorId = 1,
                            UpdatedAtUtc = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueJson = "{}"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "mapa_dominio",
                            SchemaVersion = 1,
                            TutorId = 1,
                            UpdatedAtUtc = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueJson = "{\"temas\":[]}"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "lagunas_o_errores",
                            SchemaVersion = 1,
                            TutorId = 1,
                            UpdatedAtUtc = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueJson = "{\"activas\":[],\"resueltas\":[]}"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "historial_actividades",
                            SchemaVersion = 1,
                            TutorId = 1,
                            UpdatedAtUtc = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueJson = "{\"proyectos\":[]}"
                        });
                });

            modelBuilder.Entity("LearningAgents.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("LearningAgents.Domain.Entities.StudySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TutorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("LearningAgents.Domain.Entities.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GeminiModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmProfile")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("gemini-default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPromptContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tutors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tutor de ejemplo para aprendizaje guiado de programacion.",
                            GeminiModel = "gemini-2.5-flash",
                            LlmProfile = "gemini-default",
                            Name = "Programming Tutor",
                            SystemPromptContent = "Actua como un tutor de programacion socratico y enfocado en aprendizaje real.",
                            UpdatedAtUtc = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LearningAgents.Domain.Entities.MemoryChange", b =>
                {
                    b.HasOne("LearningAgents.Domain.Entities.MemoryEntry", "MemoryEntry")
                        .WithMany("MemoryChanges")
                        .HasForeignKey("MemoryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningAgents.Domain.Entities.Message", "Message")
                        .WithMany("MemoryChanges")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MemoryEntry");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("LearningAgents.Domain.Entities.MemoryEntry", b =>
                {
                    b.HasOne("LearningAgents.Domain.Entities.Tutor", "Tutor")
                        .WithMany("MemoryEntries")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("LearningAgents.Domain.Entities.Message", b =>
                {
                    b.HasOne("LearningAgents.Domain.Entities.StudySession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LearningAgents.Domain.Entities.StudySession", b =>
                {
                    b.HasOne("LearningAgents.Domain.Entities.Tutor", "Tutor")
                        .WithMany("StudySessions")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("LearningAgents.Domain.Entities.MemoryEntry", b =>
                {
                    b.Navigation("MemoryChanges");
                });

            modelBuilder.Entity("LearningAgents.Domain.Entities.Message", b =>
                {
                    b.Navigation("MemoryChanges");
                });

            modelBuilder.Entity("LearningAgents.Domain.Entities.StudySession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("LearningAgents.Domain.Entities.Tutor", b =>
                {
                    b.Navigation("MemoryEntries");

                    b.Navigation("StudySessions");
                });
#pragma warning restore 612, 618
        }
    }
}
